# Generated by Django 3.0 on 2019-12-10 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='')),
                ('slug_group', models.CharField(max_length=255)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('superAdmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='super_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_one', models.CharField(max_length=255, null=True)),
                ('sender_two', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupe_user', to='chat_app.GroupeChat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(default='useravatar.png', upload_to='profile/')),
                ('actu', models.CharField(max_length=50)),
                ('user_slug', models.CharField(max_length=255, unique=True)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_msg', to='chat_app.Salon')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_msg', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ami_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('user_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_ami_one', to=settings.AUTH_USER_MODEL)),
                ('user_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_ami_two', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
