# Generated by Django 3.0 on 2019-12-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_slug',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
